#!/bin/sh
# 更新软件源
apk update
# 安装依赖项
apk add wget unzip openrc curl jq openssl sed

Version=`curl -sL https://api.github.com/repos/XTLS/Xray-core/releases|jq .[0].tag_name -r`
if [ -z $Version ];then
  Version="v1.8.1"
fi
read -p "将采用Xray版本为:${Version} 如需要自定义版本请输入版本号,否则请直接留空回车:" pVersion
[ -z ${pVersion} ] || Version="v"$pVersion

wget -qO xray.zip https://github.com/XTLS/Xray-core/releases/download/${Version}/Xray-linux-64.zip
unzip xray.zip -d /etc/Xray
rm xray.zip

passwd=`openssl rand -base64 32`
function choosemethod(){
        echo -e "\n1.aes-256-gcm\n2.chacha20-poly1305\n3.2022-blake3-aes-256-gcm\n4.2022-blake3-chacha20-poly1305"
        read -p "选择应用的协议:" method
        case ${method} in 
                1)
                        method="aes-256-gcm";;
                2)
                        method="chacha20-poly1305";;
                3)
                        method="2022-blake3-aes-256-gcm";;
                4)
                        method="2022-blake3-chacha20-poly1305";;
                *)
                        echo "error"
                        sleep 3s
                        choosemethod;;
        esac
}
choosemethod

share=`echo $method:$passwd|base64 -w 0`

read -p "键入监听端口:" port

cat > /etc/Xray/config.json <<EOF
{
  "log": null,
  "routing": {
    "rules": [
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "dns": null,
  "inbounds": [
      {
      "listen": "::",
      "port": $port,
      "protocol": "shadowsocks",
      "settings": {
        "method": "$method",
        "password": "$passwd",
        "network": "tcp,udp"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "acceptProxyProtocol": false
        }
      },
      "tag": "ss-in",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ]
}
EOF

echo $passwd> str
ipasswd=$passwd
sed -i "s/\+/%2B/g" str
passwd=`cat str`
rm str
ip=`curl -s ip.sb`
encode=`curl -sL https://www.toolhelper.cn/EncodeDecode/Base64Encode -d "encode=$method:$passwd" -d "encoding=UTF-8"|jq .Data -r`

chmod +x /etc/Xray/xray

# 创建 Xray 服务文件
cat > /etc/init.d/Xray <<EOF
#!/sbin/openrc-run

depend() {
    need net
}

start() {
    ebegin "Starting Xray"
    start-stop-daemon --start --exec '/etc/Xray/xray -- -config /etc/Xray/config.json > /dev/null 2>&1'
    eend $?
}

stop() {
    ebegin "Stopping Xray"
    start-stop-daemon --stop --exec /etc/Xray/xray
    eend $?
}

restart() {
    ebegin "Restarting Xray"
    start-stop-daemon --stop --exec '/etc/Xray/xray'
    sleep 1
    start-stop-daemon --start --exec '/etc/Xray/xray -- -config /etc/Xray/config.json > /dev/null 2>&1'
    eend $?
}
EOF

# 添加执行权限
chmod +x /etc/init.d/Xray

# 添加到开机启动项中
rc-update add Xray default
rc-service Xray restart > /dev/null 2>&1

echo "安装完成！"
echo -e "\nPort:"$port
echo -e "\nMethod:"$method
echo -e "\nPassword:"$ipasswd
echo -e "\nIP:"$ip
echo -e "\n分享链接(v4):ss://${encode}@${ip}:${port}#SS"
